routes/web.php
<?php

use App\Http\Controllers\AgendaInstructor;
use App\Http\Controllers\AgendainstructorController;
use App\Http\Controllers\BuypackageController;
use App\Http\Controllers\InstructeursController;
use App\Http\Controllers\PackagesController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\VacancyOverviewController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentsController;
use App\Http\Middleware\AdminCheck;
use App\Http\Middleware\InstructorCheck;
use App\Http\Middleware\StudentCheck;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




// Route::resource('/instructeurs', InstructeursController::class)->name('', 'instructeurs');
//Route::get('/instructeurs', 'InstructeursController')->name('instructeurs');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');


Route::group(['middleware' => StudentCheck::class], function () {
    
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
     Route::get('/Buy-Package', [BuypackageController::class, 'index'])->name('Buy-Package');
     Route::post('selectedPackage',[BuypackageController::class, 'selectedPackage'])->name('selectedPackage');
     Route::get('/my-packages', [BuypackageController::class, 'myPackages'])->name('my-packages');
     Route::get('/vacancy-overview', [VacancyOverviewController::class, 'userPackages'])->name('my-vacancy-overview');
    Route::get('/agenda', [StudentsController::class, 'showAgendaView'])->name('agendaview');
    Route::post('/agenda', [StudentsController::class, 'createPlanStudent'])->name('agenda.student');
    Route::get('/cancel-lessonStudent/{date}', [StudentsController::class, 'cancelLessonStudent'])->name('cancel.lessonStudent');
    Route::delete('/cancel-lessonStudent/{date}', [StudentsController::class, 'cancelLessonStudent'])->name('cancel.lessonStudent');





});


Route::group(['middleware' => AdminCheck::class], function () {
    Route::resource('/instructeurs', InstructeursController::class);
    Route::resource('/packages', PackagesController::class);
    Route::resource('/instructeurs', InstructeursController::class)->name('', 'instructeurs');


});

Route::group(['middleware' => InstructorCheck::class], function () {
    Route::get('/agendainstructor', [AgendainstructorController::class, 'index'])->name('agendainstructor');

    Route::get('/agenda-overview', [AgendainstructorController::class, 'overview'])->name('agenda.overview');

    Route::get('/cancel-lesson/{date}', [AgendaInstructor::class, 'cancelLesson'])->name('agenda.overview');

    Route::post('/agendainstructor', [AgendainstructorController::class,'createPlan'])->name('agenda.instructor');
    Route::delete('/cancel-lesson/{date}', [AgendaInstructor::class, 'cancelLesson'])->name('cancel.lesson');

});

require __DIR__.'/auth.php';

app/Http/Controllers/InstructeursController.php
<?php

namespace App\Http\Controllers;

use App\Models\AuditTrail;
use Illuminate\Http\Request;
use App\Models\login;
use App\Models\Instructors;
use App\Models\User;

use Illuminate\Auth\Events\Login as EventsLogin;
use PhpParser\Node\Stmt\Return_;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;


class InstructeursController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $instructors = Instructors::where('isActive',true)->with('login')->get();
        return view('Instructeurs.index')->with('instructors', $instructors);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

        return view('Instructeurs.add');

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // Validation rules
        $rules = [
            'email' => 'required|unique:login',
            'password' => ['required','string','min:8','regex:/[0-9]/','regex:/[@$!%*#?&]/',],
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $user = new login();
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->FKRoleId = 1;
        $user->save();

        $loginId = $user->id;

        AuditTrail::logUserRegister('instructors');

        $instructor = new Instructors();
        $instructor->FKLoginId = $loginId;
        $instructor->firstname = $request->firstname;
        $instructor->insertion = $request->insertion;
        $instructor->lastname = $request->lastname;
        $instructor->save();

        return redirect('instructeurs')->with('message', 'Instructor has been added successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {

        $instructor = Instructors::find($id);

        if ($instructor) {
            return view('instructeurs.edit', compact('instructor'));
        } else {
            return redirect()->route('instructeurs.index')->with('error', 'Instructor not found.');
        }


    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $rules = [
            'email' => 'required|string|email|max:255|unique:login,email,'.$id,
           // 'password' => ['required','string','min:8','regex:/[0-9]/','regex:/[@$!%*#?&]/'],
        ];



        $validator = Validator::make($request->all(), $rules);
        //dd($validator->getData());
        AuditTrail::logInstructorUpdateBasic($validator->getData(), 'instructors');
        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        } else {
            $instructor = Instructors::find($id);

            if (!$instructor) {
                return redirect('instructeurs')->with('message', 'Instructor not found!');
            }

            $instructor->firstname = $request->firstname;
            $instructor->insertion = $request->insertion;
            $instructor->lastname = $request->lastname;
            $instructor->save();

            $loginId = $instructor->FKLoginId;
            $login = login::find($loginId);

            if (!$login) {
                return redirect('instructeurs')->with('message', 'Login not found!');
            }

            $login->email = $request->email;
            $login->save();

            return redirect('instructeurs')->with('message', 'Instructor has been adjusted!');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $instructor = Instructors::find($id);

        if ($instructor) {
            $loginId = $instructor->FKLoginId;

            $instructor->FKLoginId = null;
            $instructor->save();

            if ($loginId) {
                Login::where('id', $loginId)->delete();
            }

            $instructor->isActive = false;
            $instructor->save();

            $students = User::where('instructor_id', $id)->get();

            foreach ($students as $student) {
                // Find a random inactive instructor
                $randomInstructor = Instructors::where('id', '!=', $id)
                    ->where('isActive', true) // Only consider active instructors
                    ->inRandomOrder()
                    ->first();

                if ($randomInstructor) {
                    // Update the instructor of the student
                    $student->instructor_id = $randomInstructor->id;
                    $student->save();
                } else {
                    // Handle the case where no active random instructor is found
                    // You can log an error, send a notification, or handle it based on your application's requirements.
                }
            }

            return redirect()->route('instructeurs.index')->with('message', 'Instructor Deleted successfully.');
        } else {
            return redirect()->route('instructeurs.index')->with('error', 'Instructor not found.');
        }
    }


}

resources/views/instructeurs/add.blade.php
@extends('layouts.manager')

@section('title', 'Add Instructeurs')

@section('content')

<div class="container">
    <div class="row">
      <div class="col-md-8 mt-4">
        <div class="card">
          <div class="card-header">
            <h3>Add instructor
            </h3>

          </div>
          <div class="card-body">
            <form action="{{ url('instructeurs') }}" method="POST" enctype="multipart/form-data">
            {!! csrf_field() !!}

                <div class="mb-3">
                    <label>Firstname*</label>
                    <input type="text" name="firstname" required class="form-control" />
                </div>
                <div class="mb-3">
                    <label>Insertion</label>
                    <input type="text" name="insertion" class="form-control"/>
                </div>

                <div class="mb-3">
                    <label>Lastname*</label>
                    <input type="text" name="lastname" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label>Email*</label>
                    <input type="text" name="email" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label>Password*</label>
                    <input type="password" name="password" class="form-control" required />
                </div>
                <div class="mb-3">
                @if ($errors->any())
                      <div class="alert alert-danger">
                          <ul>
                              @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                              @endforeach
                          </ul>
                      </div>
                 @endif
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">ADD</button>
                    <a href="{{ url('/instructeurs') }}" class="btn btn-danger float-end">BACK</a>

                </div>


            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
  @endsection

resources/views/instructeurs/edit.blade.php
@extends('layouts.manager')

@section('title', 'Edit Instructeurs')

@section('content')

<div class="container">
    <div class="row">
      <div class="col-md-8 mt-4">
        <div class="card">
          <div class="card-header">
            <h3>edit instructor
              <a href="{{ url('/instructeurs') }}" class="btn btn-danger float-end">BACK</a>
            </h3>

          </div>
          <div class="card-body">
            <form action="{{ url('instructeurs/' .$instructor->id) }}" method="POST" enctype="multipart/form-data">
               {!! csrf_field() !!}
               @method("PATCH")

               <input type="hidden" name= "id" value="{{  $instructor->id }}">


                <div class="mb-3">
                    <label>Firstname*</label>
                    <input type="text" name="firstname" value="{{ $instructor->firstname }}" required class="form-control" />
                </div>
                <div class="mb-3">
                    <label>Insertion</label>
                    <input type="text" name="insertion" value="{{ $instructor->insertion }}" class="form-control"/>
                </div>

                <div class="mb-3">
                    <label>Lastname*</label>
                    <input type="text" name="lastname" value="{{ $instructor->lastname }}" class="form-control" required />
                </div>
                <div class="mb-3">
                    <label>Email*</label>
                    <input type="text" name="email" value="{{ $instructor->login->email }}" class="form-control" required />
                </div>
                <div class="mb-3">
                       @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>


            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
  @endsection

resources/views/instructeurs/index.blade.php
@extends('layouts.manager')

@section('title', 'Instructeurs')

@section('content')


    <div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
    <span>Instructors</span>
    <a href="{{ url('/instructeurs/create') }}" class="btn btn-primary" id="addInstructorBtn">Add Instructor</a>
    </div>
    <div class="card-body">


    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Firstname</th>
      <th scope="col">Insertion</th>
      <th scope="col">Lastname</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>


    </tr>
  </thead>
  <tbody>
  @if(count($instructors) > 0)

        @if(session('message'))
            <div class="text-center">
                <p class="alert alert-secondary">{{ session('message') }}</p>
            </div>
        @endif



      @foreach( $instructors as $instructor)

    <tr>

      <td>{{$instructor->login->email}}</td>
      <td>{{$instructor->firstname}}</td>
      @if(($instructor->insertion) > 0)
      <td>{{$instructor->insertion}} </td>
      @else
      <td></td>
      @endif
      <td>{{$instructor->lastname}} </td>
      <td><a href="{{ url('/instructeurs/' . $instructor->id . '/edit') }}" class="btn btn-primary">Edit</a></td>
      <td>
      <form action="{{ route('instructeurs.destroy', ['instructeur' => $instructor->id]) }}" method="post">
          @csrf
          @method('delete') {{-- Use 'delete' method for the destroy action --}}
          <button type="submit" class="btn btn-danger"  onclick="return confirm('Are you sure you want to delete?')">Delete</button>
      </form>
      </td>
    </tr>
    @endforeach

    @else
    <p class="alert ">No instructor founded!</p>
    @endif


  </tbody>
</table>
    </div>
    </div>
@endsection